<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BotPulse.Core\BotPulse.Core.csproj" />
    <ProjectReference Include="..\BotPulse.Infrastructure\BotPulse.Infrastructure.csproj" />
    <ProjectReference Include="..\BotPulse.Providers.UiPath\BotPulse.Providers.UiPath.csproj" />
  </ItemGroup>

</Project>
