namespace BotPulse.Core.Domain.Events;

/// <summary>Raised when a job transitions to a new status.</summary>
public sealed record JobStateChanged(
    string JobExternalId,
    string ProviderName,
    string OldStatus,
    string NewStatus,
    DateTime OccurredAtUtc)
{
    public JobStateChanged(string jobExternalId, string providerName, string oldStatus, string newStatus)
        : this(jobExternalId, providerName, oldStatus, newStatus, DateTime.UtcNow) { }
}

/// <summary>Raised when an alert is generated by the Alert Engine.</summary>
public sealed record AlertRaised(
    Guid AlertId,
    Guid RuleId,
    string RuleName,
    string Severity,
    string AffectedResourceType,
    string AffectedResourceId,
    string ConditionDescription,
    DateTime OccurredAtUtc)
{
    public AlertRaised(Guid alertId, Guid ruleId, string ruleName, string severity,
        string affectedResourceType, string affectedResourceId, string conditionDescription)
        : this(alertId, ruleId, ruleName, severity, affectedResourceType, affectedResourceId, conditionDescription, DateTime.UtcNow) { }
}

/// <summary>Raised when a queue item changes processing state.</summary>
public sealed record QueueItemProcessed(
    string ExternalItemId,
    string QueueName,
    string NewStatus,
    string ProviderName,
    DateTime OccurredAtUtc)
{
    public QueueItemProcessed(string externalItemId, string queueName, string newStatus, string providerName)
        : this(externalItemId, queueName, newStatus, providerName, DateTime.UtcNow) { }
}

/// <summary>Raised when a user requests a job action (Start, Stop, Cancel, Retry).</summary>
public sealed record JobActionRequested(
    string JobExternalId,
    string Action,
    string RequestedByUserName,
    DateTime OccurredAtUtc)
{
    public JobActionRequested(string jobExternalId, string action, string requestedByUserName)
        : this(jobExternalId, action, requestedByUserName, DateTime.UtcNow) { }
}
